# This file is managed by 'repo_helper'. Don't edit it directly.
# Read the Docs configuration file
---
version: 2
sphinx:
  builder: html
  configuration: doc-source/conf.py
formats:
 - pdf
 - htmlzip
python:
  install:
   - requirements: requirements.txt
   - requirements: doc-source/requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    post_create_environment:
     - pip install .[all]
    post_install:
     - pip install sphinxcontrib-applehelp==1.0.4 sphinxcontrib-devhelp==1.0.2 sphinxcontrib-htmlhelp==2.0.1
       sphinxcontrib-jsmath==1.0.1 sphinxcontrib-qthelp==1.0.3 sphinxcontrib-serializinghtml==1.1.5
  apt_packages:
   - libgirepository1.0-dev
   - libgtk-3-dev
   - libvte-2.91-0
   - gir1.2-vte-2.91
   - libdbusmenu-glib4
   - gir1.2-dbusmenu-glib-0.4
   - libunity9
   - gir1.2-unity-5.0
   - libcairo-gobject2
   - libcairo2-dev
   - pkg-config
   - cmake
